# Generated by Django 5.2 on 2025-05-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rueruprechner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="notes",
            field=models.TextField(default="", verbose_name="Personal Notes"),
            preserve_default=False,
        ),
    ]
