# Generated by Django 5.2 on 2025-05-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rueruprechner", "0002_contract_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
