# Generated by Django 5.2 on 2025-05-04 13:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rueruprechner", "0005_vendor"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=120, unique=True)),
                (
                    "vileness",
                    models.CharField(
                        choices=[
                            ("Unknown", "Unknown"),
                            ("Mostly honest", "Mostly Honest"),
                            ("Pretty vile", "Pretty Vile"),
                            ("Pure evil", "Pure Evil"),
                        ],
                        default="Unknown",
                    ),
                ),
                (
                    "last_update",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(default="", verbose_name="Personal Notes")),
                (
                    "proposal_status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                        ],
                        default="New",
                        editable=False,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="contract",
            name="name",
            field=models.CharField(default="", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="name",
            field=models.CharField(default="", max_length=120, unique=True),
        ),
    ]
