# Generated by Django 5.2 on 2025-05-04 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rueruprechner", "0005_vendor"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorProposal",
            fields=[
                (
                    "vendor_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="rueruprechner.vendor",
                    ),
                ),
                (
                    "proposal_status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                        ],
                        default="New",
                        editable=False,
                    ),
                ),
            ],
            bases=("rueruprechner.vendor",),
        ),
    ]
