# Generated by Django 5.2 on 2025-05-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rueruprechner", "0006_vendorproposal_alter_contract_name_alter_vendor_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="name",
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
