# Generated by Django 5.2 on 2025-05-05 15:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("", "Default"),
                            ("BMW1302", "Bmw"),
                            ("SWM0047", "Swm"),
                        ],
                        default="",
                    ),
                ),
                (
                    "last_update",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(default="", verbose_name="Personal Notes")),
            ],
        ),
    ]
