# Generated by Django 5.2 on 2025-05-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capabilities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_key",
            field=models.CharField(
                choices=[("", "Default"), ("BMW1302", "Bmw"), ("SWM0047", "Swm")],
                default="",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending Confirmation", "Not Started"),
                    ("Confirmed", "Confirmed"),
                    ("Ongoing", "Ongoing"),
                    ("Done", "Done"),
                ],
                default="Pending Confirmation",
            ),
        ),
    ]
