name: Project Tests
on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v2
        with:
          python-version: 3.10.0
      - name: Run tests
        run: |
          pipenv install --default
          pipenv run pytest
