name: Django Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12  # Match your local Python version

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Add project to PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:${GITHUB_WORKSPACE}/pytest_udemy_django" >> $GITHUB_ENV

      - name: Run Django tests with pytest and coverage
        env:
          DJANGO_SETTINGS_MODULE: pytest_udemy_django.settings
        run: pipenv run pytest --cov=. --cov-report=xml --maxfail=5 --disable-warnings -v
